name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run main.go
        run: go run cmd/painter/main.go

      - name: Test loop_test.go
        run: go test ./painter/loop_test.go

      - name: Test parser_test.go
        run: go test ./painter/lang/parser_test.go
